name: Fetch anaconda.org stats
on:
  schedule:
  - cron: '0 3,9,15,21 * * *'
  workflow_dispatch:
  pull_request:

jobs:
  fetch-anaconda-org-stats:
    name: Fetch anaconda.org stats
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Fetch
      id: fetch
      run: |
        pip install aiohttp ntplib requests urllib3
        time=$( PYTHONPATH="$( pwd )/src" python -m package_downloads.stats_from_anaconda_org )
        echo "::set-output name=time::${time}"

    - name: Add changes, commit
      run: |
        if git --no-pager log -1 --oneline | grep -q '${{ steps.fetch.outputs.time }}$' ; then
          echo 'Skipping commit since daily stats already archived.'
        else
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A ./package-downloads
          git status
          git commit -m 'Update package download stats, ${{ steps.fetch.outputs.time }}'
        fi

    - if: ${{ github.ref == 'refs/heads/main' }}
      name: Push changes
      run: |
        git push
